### ISSUE TITLE
handshake_failure

### ISSUE THREAD

**Issue by kasserater** [tomato42/tlslite-ng#127]
continuing thread from [tlslite, issue 113](https://github.com/trevp/tlslite/issues/113)

call to *handshakeClientAnonymous* fails with handshake_failure

code used and error backtrace
```
import socket
from tlslite import TLSConnection
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.settimeout(5)
sock.connect((<ip>,<port>))
c = TLSConnection(socket)
c.handshakeClientAnonymous()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/<python-path>/tlslite/tlsconnection.py", line 243, in handshakeClientAnonymous
    for result in handshaker:
  File "/<python-path>/tlslite/tlsconnection.py", line 439, in _handshakeClientAsync
    for result in self._handshakeWrapperAsync(handshaker, checker):
  File "/<python-path>/tlslite/tlsconnection.py", line 2060, in _handshakeWrapperAsync
    for result in handshaker:
  File "/<python-path>/tlslite/tlsconnection.py", line 533, in _handshakeClientAsyncHelper
    for result in self._clientGetServerHello(settings, clientHello):
  File "/<python-path>/tlslite/tlsconnection.py", line 687, in _clientGetServerHello
    HandshakeType.server_hello):
  File "/<python-path>/tlslite/tlsrecordlayer.py", line 681, in _getMsg
    raise TLSRemoteAlert(alert)
tlslite.errors.TLSRemoteAlert: handshake_failure
```
* using tlslite-ng 0.5.2, not installed but using source python included in larger python project by adding the source code files to python include path
* python 2.7.5
* linux 64bit machine using IBM MCP linux flavor
* kernel 3.10.0-123.20.1
* no tlslite installed
* no virtual env in use

**Comment by sanderux** [comment]
I;m also having troube
- Python 2.7.3
- installed via pip
- cloned source
- make test
```
root@ml ~/tlslite-ng# make test
cd tests/ && python ./tlstest.py server localhost:4433 . & sleep 1
cd tests/ && python ./tlstest.py client localhost:4433 .
Test 0 - anonymous handshake
Test 0 - Anonymous server handshake
Test 1 - good X.509
Test 1 - good X509 (plus SNI)
Traceback (most recent call last):
  File "./tlstest.py", line 1279, in <module>
    clientTestCmd(sys.argv[2:])
  File "./tlstest.py", line 118, in clientTestCmd
    connection.handshakeClientCert(serverName=address[0])
  File "/usr/local/lib/python2.7/dist-packages/tlslite/tlsconnection.py", line 350, in handshakeClientCert
    for result in handshaker:
  File "/usr/local/lib/python2.7/dist-packages/tlslite/tlsconnection.py", line 366, in _handshakeClientAsync
    for result in self._handshakeWrapperAsync(handshaker, checker):
  File "/usr/local/lib/python2.7/dist-packages/tlslite/tlsconnection.py", line 1906, in _handshakeWrapperAsync
    for result in handshaker:
  File "/usr/local/lib/python2.7/dist-packages/tlslite/tlsconnection.py", line 545, in _handshakeClientAsyncHelper
    nextProto):
  File "/usr/local/lib/python2.7/dist-packages/tlslite/tlsconnection.py", line 964, in _clientFinished
    for result in self._sendFinished(masterSecret, cipherSuite, nextProto):
  File "/usr/local/lib/python2.7/dist-packages/tlslite/tlsconnection.py", line 1847, in _sendFinished
    for result in self._sendMsg(finished):
  File "/usr/local/lib/python2.7/dist-packages/tlslite/tlsrecordlayer.py", line 590, in _sendMsg
    for result in self._sendMsgThroughSocket(msgFragment):
  File "/usr/local/lib/python2.7/dist-packages/tlslite/tlsrecordlayer.py", line 597, in _sendMsgThroughSocket
    for result in self._recordLayer.sendRecord(msg):
  File "/usr/local/lib/python2.7/dist-packages/tlslite/recordlayer.py", line 469, in sendRecord
    data = self._encryptThenSeal(data, contentType)
  File "/usr/local/lib/python2.7/dist-packages/tlslite/recordlayer.py", line 417, in _encryptThenSeal
    buf = self._writeState.encContext.seal(nonce, buf, authData)
  File "/usr/local/lib/python2.7/dist-packages/tlslite/utils/chacha20_poly1305.py", line 55, in seal
    otk = self.poly1305_key_gen(self.key, nonce)
  File "/usr/local/lib/python2.7/dist-packages/tlslite/utils/chacha20_poly1305.py", line 36, in poly1305_key_gen
    poly = ChaCha(key, nonce)
  File "/usr/local/lib/python2.7/dist-packages/tlslite/utils/chacha.py", line 137, in __init__
    self.key = ChaCha._bytearray_to_words(key)
  File "/usr/local/lib/python2.7/dist-packages/tlslite/utils/chacha.py", line 122, in _bytearray_to_words
    compat26Str(data[i*4:(i+1)*4])))
struct.error: unpack requires a string argument of length 4
make: *** [test] Error 1
root@ml ~/tlslite-ng# Traceback (most recent call last):
  File "./tlstest.py", line 1281, in <module>
    serverTestCmd(sys.argv[2:])
  File "./tlstest.py", line 764, in serverTestCmd
    connection.handshakeServer(certChain=x509Chain, privateKey=x509Key)
  File "/usr/local/lib/python2.7/dist-packages/tlslite/tlsconnection.py", line 1102, in handshakeServer
    nextProtos=nextProtos, anon=anon):
  File "/usr/local/lib/python2.7/dist-packages/tlslite/tlsconnection.py", line 1131, in handshakeServerAsync
    for result in self._handshakeWrapperAsync(handshaker, checker):
  File "/usr/local/lib/python2.7/dist-packages/tlslite/tlsconnection.py", line 1906, in _handshakeWrapperAsync
    for result in handshaker:
  File "/usr/local/lib/python2.7/dist-packages/tlslite/tlsconnection.py", line 1316, in _handshakeServerAsyncHelper
    nextProtos):
  File "/usr/local/lib/python2.7/dist-packages/tlslite/tlsconnection.py", line 1807, in _serverFinished
    expect_next_protocol=nextProtos is not None):
  File "/usr/local/lib/python2.7/dist-packages/tlslite/tlsconnection.py", line 1895, in _getFinished
    HandshakeType.finished):
  File "/usr/local/lib/python2.7/dist-packages/tlslite/tlsrecordlayer.py", line 646, in _getMsg
    for result in self._getNextRecord():
  File "/usr/local/lib/python2.7/dist-packages/tlslite/tlsrecordlayer.py", line 817, in _getNextRecord
    for result in self._getNextRecordFromSocket():
  File "/usr/local/lib/python2.7/dist-packages/tlslite/tlsrecordlayer.py", line 841, in _getNextRecordFromSocket
    for result in self._recordLayer.recvRecord():
  File "/usr/local/lib/python2.7/dist-packages/tlslite/recordlayer.py", line 695, in recvRecord
    for result in self._recordSocket.recv():
  File "/usr/local/lib/python2.7/dist-packages/tlslite/recordlayer.py", line 188, in recv
    for record in self._recvHeader():
  File "/usr/local/lib/python2.7/dist-packages/tlslite/recordlayer.py", line 122, in _recvHeader
    for result in self._sockRecvAll(1):
  File "/usr/local/lib/python2.7/dist-packages/tlslite/recordlayer.py", line 109, in _sockRecvAll
    raise TLSAbruptCloseError()
tlslite.errors.TLSAbruptCloseError: TLSAbruptCloseError()
```


running regular example:
```
root@ml tlslite-ng/tests# tls.py server -k serverX509Key.pem -c serverX509Cert.pem localhost:4443
I am an HTTPS test server, I will listen on localhost:4443
Serving files from /root/tlslite-ng/tests
Using certificate and private key...
About to handshake...
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 48303)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/dist-packages/tlslite/integration/tlssocketservermixin.py", line 55, in finish_request
    if self.handshake(tlsConnection) == True:
  File "/usr/local/bin/tls.py", line 345, in handshake
    reqCert=reqCert)
  File "/usr/local/lib/python2.7/dist-packages/tlslite/tlsconnection.py", line 1102, in handshakeServer
    nextProtos=nextProtos, anon=anon):
  File "/usr/local/lib/python2.7/dist-packages/tlslite/tlsconnection.py", line 1131, in handshakeServerAsync
    for result in self._handshakeWrapperAsync(handshaker, checker):
  File "/usr/local/lib/python2.7/dist-packages/tlslite/tlsconnection.py", line 1906, in _handshakeWrapperAsync
    for result in handshaker:
  File "/usr/local/lib/python2.7/dist-packages/tlslite/tlsconnection.py", line 1316, in _handshakeServerAsyncHelper
    nextProtos):
  File "/usr/local/lib/python2.7/dist-packages/tlslite/tlsconnection.py", line 1807, in _serverFinished
    expect_next_protocol=nextProtos is not None):
  File "/usr/local/lib/python2.7/dist-packages/tlslite/tlsconnection.py", line 1895, in _getFinished
    HandshakeType.finished):
  File "/usr/local/lib/python2.7/dist-packages/tlslite/tlsrecordlayer.py", line 646, in _getMsg
    for result in self._getNextRecord():
  File "/usr/local/lib/python2.7/dist-packages/tlslite/tlsrecordlayer.py", line 817, in _getNextRecord
    for result in self._getNextRecordFromSocket():
  File "/usr/local/lib/python2.7/dist-packages/tlslite/tlsrecordlayer.py", line 841, in _getNextRecordFromSocket
    for result in self._recordLayer.recvRecord():
  File "/usr/local/lib/python2.7/dist-packages/tlslite/recordlayer.py", line 695, in recvRecord
    for result in self._recordSocket.recv():
  File "/usr/local/lib/python2.7/dist-packages/tlslite/recordlayer.py", line 188, in recv
    for record in self._recvHeader():
  File "/usr/local/lib/python2.7/dist-packages/tlslite/recordlayer.py", line 122, in _recvHeader
    for result in self._sockRecvAll(1):
  File "/usr/local/lib/python2.7/dist-packages/tlslite/recordlayer.py", line 109, in _sockRecvAll
    raise TLSAbruptCloseError()
TLSAbruptCloseError: TLSAbruptCloseError()
----------------------------------------
```

Response from client

```
root@ml tlslite-ng/tests# tls.py client localhost:4443                          Traceback (most recent call last):
  File "/usr/local/bin/tls.py", line 387, in <module>
    clientCmd(sys.argv[2:])
  File "/usr/local/bin/tls.py", line 264, in clientCmd
    settings=settings, serverName=address[0])
  File "/usr/local/lib/python2.7/dist-packages/tlslite/tlsconnection.py", line 350, in handshakeClientCert
    for result in handshaker:
  File "/usr/local/lib/python2.7/dist-packages/tlslite/tlsconnection.py", line 366, in _handshakeClientAsync
    for result in self._handshakeWrapperAsync(handshaker, checker):
  File "/usr/local/lib/python2.7/dist-packages/tlslite/tlsconnection.py", line 1906, in _handshakeWrapperAsync
    for result in handshaker:
  File "/usr/local/lib/python2.7/dist-packages/tlslite/tlsconnection.py", line 545, in _handshakeClientAsyncHelper
    nextProto):
  File "/usr/local/lib/python2.7/dist-packages/tlslite/tlsconnection.py", line 964, in _clientFinished
    for result in self._sendFinished(masterSecret, cipherSuite, nextProto):
  File "/usr/local/lib/python2.7/dist-packages/tlslite/tlsconnection.py", line 1847, in _sendFinished
    for result in self._sendMsg(finished):
  File "/usr/local/lib/python2.7/dist-packages/tlslite/tlsrecordlayer.py", line 590, in _sendMsg
    for result in self._sendMsgThroughSocket(msgFragment):
  File "/usr/local/lib/python2.7/dist-packages/tlslite/tlsrecordlayer.py", line 597, in _sendMsgThroughSocket
    for result in self._recordLayer.sendRecord(msg):
  File "/usr/local/lib/python2.7/dist-packages/tlslite/recordlayer.py", line 469, in sendRecord
    data = self._encryptThenSeal(data, contentType)
  File "/usr/local/lib/python2.7/dist-packages/tlslite/recordlayer.py", line 417, in _encryptThenSeal
    buf = self._writeState.encContext.seal(nonce, buf, authData)
  File "/usr/local/lib/python2.7/dist-packages/tlslite/utils/chacha20_poly1305.py", line 55, in seal
    otk = self.poly1305_key_gen(self.key, nonce)
  File "/usr/local/lib/python2.7/dist-packages/tlslite/utils/chacha20_poly1305.py", line 36, in poly1305_key_gen
    poly = ChaCha(key, nonce)
  File "/usr/local/lib/python2.7/dist-packages/tlslite/utils/chacha.py", line 137, in __init__
    self.key = ChaCha._bytearray_to_words(key)
  File "/usr/local/lib/python2.7/dist-packages/tlslite/utils/chacha.py", line 122, in _bytearray_to_words
    compat26Str(data[i*4:(i+1)*4])))
struct.error: unpack requires a string argument of length 4

```

@tomato42 any help appreciated

**Comment by kasserater** [comment]
@sanderux your issue is not related to the handshake_failure
please open a different issue thread

**Comment by tomato42** [comment]
I'm on vacation now, I'll get to your problems first thing next week.

**Comment by kasserater** [comment]
@tomato42 do you need any more info from me to resolve this issue?

**Comment by tomato42** [comment]
Sorry for the delay, it doesn't look like I need any more information.

In your example code:
```
import socket
from tlslite import TLSConnection
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.settimeout(5)
sock.connect((<ip>,<port>))
c = TLSConnection(socket)
```
it should be `sock` not `socket`
```
c.handshakeClientAnonymous()
```

**Comment by kasserater** [comment]
i tried with handshakeClientSRP, but received error
`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/xiv/python/tlslite/TLSConnection.py", line 213, in handshakeClientSRP
    for result in handshaker:
  File "/xiv/python/tlslite/TLSConnection.py", line 324, in _handshakeClientAsync
    for result in self._handshakeWrapperAsync(handshaker, checker):
  File "/xiv/python/tlslite/TLSConnection.py", line 1777, in _handshakeWrapperAsync
    for result in handshaker:
  File "/xiv/python/tlslite/TLSConnection.py", line 418, in _handshakeClientAsyncHelper
    for result in self._clientGetServerHello(settings, clientHello):
  File "/xiv/python/tlslite/TLSConnection.py", line 559, in _clientGetServerHello
    HandshakeType.server_hello):
  File "/xiv/python/tlslite/TLSRecordLayer.py", line 674, in _getMsg
    for result in self._getNextRecord():
  File "/xiv/python/tlslite/TLSRecordLayer.py", line 849, in _getNextRecord
    raise TLSAbruptCloseError()
`
i thought maybe because i was missing call to handshakeClientCert, but fails also
`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/xiv/python/tlslite/TLSConnection.py", line 308, in handshakeClientCert
    for result in handshaker:
  File "/xiv/python/tlslite/TLSConnection.py", line 324, in _handshakeClientAsync
    for result in self._handshakeWrapperAsync(handshaker, checker):
  File "/xiv/python/tlslite/TLSConnection.py", line 1777, in _handshakeWrapperAsync
    for result in handshaker:
  File "/xiv/python/tlslite/TLSConnection.py", line 418, in _handshakeClientAsyncHelper
    for result in self._clientGetServerHello(settings, clientHello):
  File "/xiv/python/tlslite/TLSConnection.py", line 559, in _clientGetServerHello
    HandshakeType.server_hello):
  File "/xiv/python/tlslite/TLSRecordLayer.py", line 722, in _getMsg
    raise TLSRemoteAlert(alert)
tlslite.errors.TLSRemoteAlert: handshake_failure
`

**Comment by tomato42** [comment]
both `handshakeClientSRP` and `handshakeClientAnonymous` require uncommon server configurations

for the `handshakeClientCert` the line `tlslite.errors.TLSRemoteAlert: handshake_failure` indicates that the _server_ have sent you a "handshake failure" alert message, so the _server_ rejected the connection

How is the server you are trying to connect to configured? What cipher and protocol version is negotiated by `openssl s_client`? Can you connect to it with `openssl s_client -cipher DEFAULT:-ECDSA`?

**Comment by kasserater** [comment]
when trying your suggest s_client command i receive
```
WARNING: can't open config file: /etc/pki/tls/openssl.cnf
socket: Connection refused
connect:errno=111
```

**Comment by tomato42** [comment]
did you provide to s_client where to connect to?

Full command line for youtube.com looks like this:
```
openssl s_client -connect youtube.com:443 -servername youtube.com -cipher DEFAULT:-ECDSA
```

**Comment by kasserater** [comment]
ok, added the missing params and get the following

```
CONNECTED(00000003)
140651128158112:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:s23_clnt.c:744:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 248 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
---
````

**Comment by kasserater** [comment]
the ciphers allowed by the server are
aes256 - 0x0056
aes128 - 0x0053
3des - 0x0050

**Comment by tomato42** [comment]
Those are not standard ciphers, they come from a [draft](https://tools.ietf.org/html/draft-ietf-tls-srp-02) while tlslite-ng and OpenSSL implements the published [RFC 5054](https://tools.ietf.org/html/rfc5054)

**Comment by kasserater** [comment]
understandable
thing is - my application works with tlslite version 0.3.8...

**Comment by tomato42** [comment]
it may be because 0.3.8 implements the draft not the final version.

I would strongly suggest to update the server, since it looks like it implements only the draft, it would indicate it was't updated since 2002... Lack of TLSv1.2 in such situation is rather minor issue...

**Comment by kasserater** [comment]
looking at RFC 5054 Ciphersuite Definitions chapter, the above ciphers are indeed supported:
TLS_SRP_SHA_WITH_3DES_EDE_CBC_SHA
TLS_SRP_SHA_WITH_AES_256_CBC_SHA
TLS_SRP_SHA_WITH_AES_128_CBC_SHA

**Comment by tomato42** [comment]
so if you update both server and client, it still works?

then I guess we can close this issue, can't we?

**Comment by kasserater** [comment]
no, i update both, but it doesn't work after the update

**Comment by tomato42** [comment]
then what's the problem now? does `make test-local` pass?

what's the server and client configuration?

**Comment by kasserater** [comment]
i do not install the library, rather use the source code in my project
what info do you mean by server/client configuration?

**Comment by tomato42** [comment]
> i do not install the library, rather use the source code in my project

I know, that's why I'm asking for `make test-local` it doesn't require installation to run

> what info do you mean by server/client configuration?

preferably, full minimal reproducer - with the way to generate server certificate (if any), server verify db configuration, exact commands or code to run the server and the same for client

There already are SRP test cases in the tests run through `make test` or `make test-local`, so if SRP doesn't work for You, it's a non obvious issue

**Comment by kasserater** [comment]
as this is sensitive company info, i will look into the test and test-local examples to try and figure out what is wrong with my implementation.

i will close for now, until i find an exact issue or need more help

**Comment by kasserater** [comment]
Hi @tomato42 

i tried again with latest 0.6.0 master (hash e6182d5), connecting with handshakeClientSRP
this fails with error traceback
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/xiv/python/tlslite/tlsconnection.py", line 257, in handshakeClientSRP
    for result in handshaker:
  File "/xiv/python/tlslite/tlsconnection.py", line 371, in _handshakeClientAsync
    for result in self._handshakeWrapperAsync(handshaker, checker):
  File "/xiv/python/tlslite/tlsconnection.py", line 1903, in _handshakeWrapperAsync
    for result in handshaker:
  File "/xiv/python/tlslite/tlsconnection.py", line 550, in _handshakeClientAsyncHelper
    nextProto):
  File "/xiv/python/tlslite/tlsconnection.py", line 957, in _clientFinished
    self._handshake_hash)
  File "/xiv/python/tlslite/mathtls.py", line 97, in calcExtendedMasterSecret
    48)
  File "/xiv/python/tlslite/mathtls.py", line 58, in PRF_1_2
    return P_hash(HMAC_SHA256, secret, label + seed, length)
  File "/xiv/python/tlslite/mathtls.py", line 32, in P_hash
    A = macFunc(secret, A)
  File "/xiv/python/tlslite/utils/cryptomath.py", line 107, in HMAC_SHA256
    return secureHMAC(k, b, 'sha256')
  File "/xiv/python/tlslite/utils/cryptomath.py", line 98, in secureHMAC
    return bytearray(hmac.new(k, b, getattr(hashlib, algorithm)).digest())
  File "/xiv/python/tlslite/utils/hmac.py", line 104, in new
    return HMAC(key, msg, digestmod)
  File "/xiv/python/tlslite/utils/hmac.py", line 39, in __init__
    self.outer = digestmod.new()
AttributeError: 'builtin_function_or_method' object has no attribute 'new'
```

**Comment by tomato42** [comment]
`tlslite/utils/hmac.py` - there is no such file in tlslite-ng at this revision and it was removed from tlslite "ages" ago (in 2012: d6af9b9724e153)

please try to reproduce in clean environment

**Comment by kasserater** [comment]
make sense as i just copied tlslite-ng over tlslite (which was version 0.3.8)
cleaned and tested, still getting TLSAbruptCloseError

will have to check `make test-local`

**Comment by tomato42** [comment]
Both `TLSAbruptCloseError` and `tlslite.errors.TLSRemoteAlert: handshake_failure` mean that the *other* side of the connection rejected or closed connection. It's not a bug in code, it just reports what the other side did. To say anything else I need to know why the other side of connection does that.

**Comment by tomato42** [comment]
FYI: I plan to release current master as version 0.6.0 in the next few days to a week (unless we identify that it's a bug in tlslite-ng code that causes your problems)

**Comment by kasserater** [comment]
i made a minimal server and successfully connected using handshakeClientSRP, so this seems to be an issue with my server implementation

closing

**Comment by kasserater** [comment]
@tomato42  any update when version 0.6.0 will be released?

**Comment by tomato42** [comment]
as soon as I find an hour of time to prepare packages and push them to pypi

**Comment by tomato42** [comment]
aaand done. Have fun! :)

**Comment by kasserater** [comment]
thanks!
