### ISSUE TITLE
Getting Error when trying to use

### ISSUE THREAD

**Issue by GRRedWings** [tomato42/tlslite-ng#162]
I'm guessing I have something setup wrong with my environment, but when I run the setup.py and then the tests.py steps documented in the readme I get the following error in the client window

Test 4 - SRP faults
  Good Fault bad username
  Good Fault bad password
Traceback (most recent call last):
  File "C:\Users\Brian Spratke\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tlslite\tlsrecordlayer.py", line 620, in _sendMsg
    bytesSent = self.sock.send(s) #Might raise socket.error
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tlstest.py", line 981, in <module>
    clientTestCmd(sys.argv[2:])
  File "tlstest.py", line 182, in clientTestCmd
    connection.handshakeClientSRP("test", "password")
  File "C:\Users\Brian Spratke\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tlslite\tlsconnection.py", line 213, in handshakeClientSRP
    for result in handshaker:
  File "C:\Users\Brian Spratke\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tlslite\tlsconnection.py", line 324, in _handshakeClientAsync
    for result in self._handshakeWrapperAsync(handshaker, checker):
  File "C:\Users\Brian Spratke\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tlslite\tlsconnection.py", line 1777, in _handshakeWrapperAsync
    for result in handshaker:
  File "C:\Users\Brian Spratke\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tlslite\tlsconnection.py", line 484, in _handshakeClientAsyncHelper
    nextProto):
  File "C:\Users\Brian Spratke\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tlslite\tlsconnection.py", line 943, in _clientFinished
    for result in self._sendFinished(masterSecret, nextProto):
  File "C:\Users\Brian Spratke\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tlslite\tlsconnection.py", line 1692, in _sendFinished
    for result in self._sendMsg(finished):
  File "C:\Users\Brian Spratke\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tlslite\tlsrecordlayer.py", line 640, in _sendMsg
    for result in self._getNextRecord():
  File "C:\Users\Brian Spratke\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tlslite\tlsrecordlayer.py", line 839, in _getNextRecord
    s = self.sock.recv(recordHeaderLength-len(b))
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

**Comment by tomato42** [comment]
could you run the server and client part in separate terminals and provide both outputs?

instead of running make test, please run, with CWD being `tests`, in one terminal:
```
PYTHONPATH=.. python ./tlstest.py server localhost:4433 .
```

and in other
```
PYTHONPATH=.. python ./tlstest.py client localhost:4433 .
```

**Comment by GRRedWings** [comment]
Here is the full output of both

Server:
Test 0 - Anonymous server handshake
Test 1 - good X.509
Test 1.a - good X.509, SSL v3
Test 1.b - good X.509, RC4-MD5
Test 3 - good SRP
Test 4 - SRP faults


Client:
Test 0 - anonymous handshake
Test 1 - good X509 (plus SNI)
Test 1.a - good X509, SSLv3
Test 1.b - good X509, RC4-MD5
Test 3 - good SRP
Test 4 - SRP faults
  Good Fault bad username
  Good Fault bad password
Traceback (most recent call last):
  File "C:\Python34\lib\tlslite\tlsrecordlayer.py", line 620, in _sendMsg
    bytesSent = self.sock.send(s) #Might raise socket.error
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tlstest.py", line 981, in <module>
    clientTestCmd(sys.argv[2:])
  File "tlstest.py", line 182, in clientTestCmd
    connection.handshakeClientSRP("test", "password")
  File "C:\Python34\lib\tlslite\tlsconnection.py", line 213, in handshakeClientSRP
    for result in handshaker:
  File "C:\Python34\lib\tlslite\tlsconnection.py", line 324, in _handshakeClientAsync
    for result in self._handshakeWrapperAsync(handshaker, checker):
  File "C:\Python34\lib\tlslite\tlsconnection.py", line 1777, in _handshakeWrapperAsync
    for result in handshaker:
  File "C:\Python34\lib\tlslite\tlsconnection.py", line 484, in _handshakeClientAsyncHelper
    nextProto):
  File "C:\Python34\lib\tlslite\tlsconnection.py", line 943, in _clientFinished
    for result in self._sendFinished(masterSecret, nextProto):
  File "C:\Python34\lib\tlslite\tlsconnection.py", line 1692, in _sendFinished
    for result in self._sendMsg(finished):
  File "C:\Python34\lib\tlslite\tlsrecordlayer.py", line 640, in _sendMsg
    for result in self._getNextRecord():
  File "C:\Python34\lib\tlslite\tlsrecordlayer.py", line 839, in _getNextRecord
    s = self.sock.recv(recordHeaderLength-len(b))
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

**Comment by tomato42** [comment]
so the server doesn't rise any exception?

**Comment by tomato42** [comment]
Also, which Python and on which OS is it running?

**Comment by tomato42** [comment]
Last thing, are you running the latests stable release? `tlslite-ng v.0.6.0`?

**Comment by GRRedWings** [comment]
I have tried with Python 3.4.1 and Python 3.6 (downloaded today).  Both are running on Windows 10.

I do not see any errors on the server side. I am running 0.4.9, I'll try 0.6.0, I had just pulled it off https://pypi.python.org/pypi/tlslite

**Comment by tomato42** [comment]
https://pypi.python.org/pypi/tlslite is the old repo, packages from this one are at https://pypi.python.org/pypi/tlslite-ng

**Comment by GRRedWings** [comment]
I'm having better results with 0.6.0.  My test request I was trying to do seems to work, but tests still throw error

Server:
Test 0 - Anonymous server handshake
Test 1 - good X.509
Test 2 - good X.509, SSL v3
Test 3 - good X.509, RC4-MD5
Test 4 - good X.509, TACK...skipped (no tackpy)
Test 5 - good X.509, TACK unrelated to cert chain...skipped (no tackpy)
Test 6 - good SRP
Test 7 - good SRP (db)
Traceback (most recent call last):
  File "tlstest.py", line 1312, in <module>
    serverTestCmd(sys.argv[2:])
  File "tlstest.py", line 879, in serverTestCmd
    os.remove(db_name)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\MyUser\\AppData\\Local\\Temp\\tmp__q903n2'

Client:
Test 0 - anonymous handshake
Test 1 - good X509 (plus SNI)
Test 2 - good X509, SSLv3
Test 3 - good X509, RC4-MD5
Test 4 - good X.509, TACK...skipped (no tackpy)
Test 5 - good X.509, TACK unrelated to cert chain...skipped (no tackpy)
Test 6 - good SRP
Test 7 - good SRP (db)
Test 8 - SRP faults
Traceback (most recent call last):
  File "tlstest.py", line 1310, in <module>
    clientTestCmd(sys.argv[2:])
  File "tlstest.py", line 222, in clientTestCmd
    connection.handshakeClientSRP("test", "password")
  File "C:\Python34\lib\tlslite\tlsconnection.py", line 257, in handshakeClientSRP
    for result in handshaker:
  File "C:\Python34\lib\tlslite\tlsconnection.py", line 379, in _handshakeClientAsync
    for result in self._handshakeWrapperAsync(handshaker, checker):
  File "C:\Python34\lib\tlslite\tlsconnection.py", line 2082, in _handshakeWrapperAsync
    for result in handshaker:
  File "C:\Python34\lib\tlslite\tlsconnection.py", line 476, in _handshakeClientAsyncHelper
    for result in self._clientGetServerHello(settings, clientHello):
  File "C:\Python34\lib\tlslite\tlsconnection.py", line 695, in _clientGetServerHello
    HandshakeType.server_hello):
  File "C:\Python34\lib\tlslite\tlsrecordlayer.py", line 653, in _getMsg
    for result in self._getNextRecord():
  File "C:\Python34\lib\tlslite\tlsrecordlayer.py", line 825, in _getNextRecord
    for result in self._getNextRecordFromSocket():
  File "C:\Python34\lib\tlslite\tlsrecordlayer.py", line 849, in _getNextRecordFromSocket
    for result in self._recordLayer.recvRecord():
  File "C:\Python34\lib\tlslite\recordlayer.py", line 695, in recvRecord
    for result in self._recordSocket.recv():
  File "C:\Python34\lib\tlslite\recordlayer.py", line 188, in recv
    for record in self._recvHeader():
  File "C:\Python34\lib\tlslite\recordlayer.py", line 122, in _recvHeader
    for result in self._sockRecvAll(1):
  File "C:\Python34\lib\tlslite\recordlayer.py", line 99, in _sockRecvAll
    socketBytes = self.sock.recv(length - len(buf))
  File "C:\Python34\lib\tlslite\bufferedsocket.py", line 54, in recv
    return self.socket.recv(bufsize)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

**Comment by tomato42** [comment]
Looks like Python on Windows doesn't follow its documentation (the process is supposed to be responsible for deleting the file, not OS on file close).

Please try this workaround:
```
diff --git a/tests/tlstest.py b/tests/tlstest.py
index aea82a9..dfb81f7 100755
--- a/tests/tlstest.py
+++ b/tests/tlstest.py
@@ -865,6 +865,7 @@ def serverTestCmd(argv):
         os.close(db_file)
         # this is race'y but the interface dbm interface is stupid like that...
         os.remove(db_name)
+        db_name += '-db'
         verifierDB = VerifierDB(db_name)
         verifierDB.create()
         entry = VerifierDB.makeVerifier("test", "password", 1536)
```

**Comment by tomato42** [comment]
can also be a issue with file extensions automatically added by dbm module... could you check if in `C:\Users\MyUser\AppData\Local\Temp\` there are no files that have a name that starts with `tmp__q903n2`?

**Comment by GRRedWings** [comment]
After the line delete and add. I can verify that the tmp file in the server logs is there as a .dat file. 

Server:
Test 0 - Anonymous server handshake
Test 1 - good X.509
Test 2 - good X.509, SSL v3
Test 3 - good X.509, RC4-MD5
Test 4 - good X.509, TACK...skipped (no tackpy)
Test 5 - good X.509, TACK unrelated to cert chain...skipped (no tackpy)
Test 6 - good SRP
Test 7 - good SRP (db)
Traceback (most recent call last):
  File "tlstest.py", line 1313, in <module>
    serverTestCmd(sys.argv[2:])
  File "tlstest.py", line 880, in serverTestCmd
    os.remove(db_name)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\MyUser\\spratkbd\\AppData\\Local\\Temp\\tmpq22z2jom-db'

Client:
Test 0 - anonymous handshake
Test 1 - good X509 (plus SNI)
Test 2 - good X509, SSLv3
Test 3 - good X509, RC4-MD5
Test 4 - good X.509, TACK...skipped (no tackpy)
Test 5 - good X.509, TACK unrelated to cert chain...skipped (no tackpy)
Test 6 - good SRP
Test 7 - good SRP (db)
Test 8 - SRP faults
Traceback (most recent call last):
  File "tlstest.py", line 1311, in <module>
    clientTestCmd(sys.argv[2:])
  File "tlstest.py", line 222, in clientTestCmd
    connection.handshakeClientSRP("test", "password")
  File "C:\Python34\lib\tlslite\tlsconnection.py", line 257, in handshakeClientSRP
    for result in handshaker:
  File "C:\Python34\lib\tlslite\tlsconnection.py", line 379, in _handshakeClientAsync
    for result in self._handshakeWrapperAsync(handshaker, checker):
  File "C:\Python34\lib\tlslite\tlsconnection.py", line 2082, in _handshakeWrapperAsync
    for result in handshaker:
  File "C:\Python34\lib\tlslite\tlsconnection.py", line 476, in _handshakeClientAsyncHelper
    for result in self._clientGetServerHello(settings, clientHello):
  File "C:\Python34\lib\tlslite\tlsconnection.py", line 695, in _clientGetServerHello
    HandshakeType.server_hello):
  File "C:\Python34\lib\tlslite\tlsrecordlayer.py", line 653, in _getMsg
    for result in self._getNextRecord():
  File "C:\Python34\lib\tlslite\tlsrecordlayer.py", line 825, in _getNextRecord
    for result in self._getNextRecordFromSocket():
  File "C:\Python34\lib\tlslite\tlsrecordlayer.py", line 849, in _getNextRecordFromSocket
    for result in self._recordLayer.recvRecord():
  File "C:\Python34\lib\tlslite\recordlayer.py", line 695, in recvRecord
    for result in self._recordSocket.recv():
  File "C:\Python34\lib\tlslite\recordlayer.py", line 188, in recv
    for record in self._recvHeader():
  File "C:\Python34\lib\tlslite\recordlayer.py", line 122, in _recvHeader
    for result in self._sockRecvAll(1):
  File "C:\Python34\lib\tlslite\recordlayer.py", line 99, in _sockRecvAll
    socketBytes = self.sock.recv(length - len(buf))
  File "C:\Python34\lib\tlslite\bufferedsocket.py", line 54, in recv
    return self.socket.recv(bufsize)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

**Comment by tomato42** [comment]
Let's try it like this:
```
diff --git a/tests/tlstest.py b/tests/tlstest.py
index e4f225d..1003101 100755
--- a/tests/tlstest.py
+++ b/tests/tlstest.py
@@ -876,7 +876,12 @@ def serverTestCmd(argv):
         testConnServer(connection)
         connection.close()
     finally:
-        os.remove(db_name)
+        try:
+            os.remove(db_name)
+        except FileNotFoundError:
+            # dbm module may create files with different names depending on
+            # platform
+            os.remove(db_name + ".dat")
 
     test_no += 1
```

**Comment by GRRedWings** [comment]
Something is going on with that file.  I added the logic below where you had it, as well as in the finally around line 886, but then it starts to fail on the SRP faults test with the file name as well

        if os.path.exists(db_name + ".dat"):
             os.remove(db_name + ".dat")


Test 0 - Anonymous server handshake
Test 1 - good X.509
Test 2 - good X.509, SSL v3
Test 3 - good X.509, RC4-MD5
Test 4 - good X.509, TACK...skipped (no tackpy)
Test 5 - good X.509, TACK unrelated to cert chain...skipped (no tackpy)
Test 6 - good SRP
Test 7 - good SRP (db)
Test 8 - SRP faults
Traceback (most recent call last):
  File "tlstest.py", line 1322, in <module>
    serverTestCmd(sys.argv[2:])
  File "tlstest.py", line 898, in serverTestCmd
    connection.handshakeServer(verifierDB=verifierDB)
  File "C:\Python34\lib\tlslite\tlsconnection.py", line 1170, in handshakeServer
    nextProtos=nextProtos, anon=anon, alpn=alpn):
  File "C:\Python34\lib\tlslite\tlsconnection.py", line 1199, in handshakeServerAsync
    for result in self._handshakeWrapperAsync(handshaker, checker):
  File "C:\Python34\lib\tlslite\tlsconnection.py", line 2082, in _handshakeWrapperAsync
    for result in handshaker:
  File "C:\Python34\lib\tlslite\tlsconnection.py", line 1352, in _handshakeServerAsyncHelper
    settings):
  File "C:\Python34\lib\tlslite\tlsconnection.py", line 1762, in _serverSRPKeyExchange
    serverKeyExchange = keyExchange.makeServerKeyExchange(sigHash)
  File "C:\Python34\lib\tlslite\keyexchange.py", line 493, in makeServerKeyExchange
    entry = self.verifierDB[srpUsername]
  File "C:\Python34\lib\tlslite\basedb.py", line 59, in __getitem__
    valueStr = self.db[username]
  File "C:\Python34\lib\dbm\dumb.py", line 130, in __getitem__
    f = _io.open(self._datfile, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\spratkbd\\AppData\\Local\\Temp\\tmpuycd4yf9.dat'

**Comment by tomato42** [comment]
> Something is going on with that file. I added the logic below where you had it, as well as in the finally around line 886, but then it starts to fail on the SRP faults test with the file name as well

oh, the subsequent tests depend on existence of database, but it's being deleted, so they fail.

Could you try the branch in #164 - I moved the file db test before the memory db test

**Comment by GRRedWings** [comment]
With that branch I am able to run the tests clean.  

Client:
Test 48 - Internet servers test
Non-critical error: socket error trying to reach internet server:  [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
Test succeeded, 48 good

Server:
127.0.0.1 - - [26/Apr/2017 12:02:48] "POST /RPC2 HTTP/1.1" 200 -
Test succeeded

**Comment by tomato42** [comment]
So it's a test script only issue. I won't be backporting it to stable branch.
