### ISSUE TITLE
CI run failures - tlstest.py

### ISSUE THREAD

**Issue by tomato42** [tomato42/tlslite-ng#219]
CI sometimes fails, track here failures caused by `tlstest.py` but not by code changes so that we can try guessing how to fix/workaround it.

**Comment by tomato42** [comment]
```
Test 7 - good X.509, TACK...skipped (no tackpy)
Test 8 - good X.509, TACK unrelated to cert chain...skipped (no tackpy)
Test 9 - good SRP (db)
Test 7 - good X.509, TACK...skipped (no tackpy)
Test 8 - good X.509, TACK unrelated to cert chain...skipped (no tackpy)
Test 9 - good SRP (db)
Traceback (most recent call last):
  File "./tlstest.py", line 1472, in <module>
    clientTestCmd(sys.argv[2:])
  File "./tlstest.py", line 242, in clientTestCmd
    synchro.recv(1)
socket.timeout: timed out
make: *** [test-local] Error 1
```

**Comment by tomato42** [comment]
Slow machine
```
The job exceeded the maximum time limit for jobs, and has been terminated.
```
with
```
Ran 1231 tests in 37.974s
```

**Comment by tomato42** [comment]
```
======================================================================
ERROR: test_connection_no_rsa_pss (unit_tests.test_tlslite_tlsconnection.TestRealConnection)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/tomato42/tlslite-ng/unit_tests/test_tlslite_tlsconnection.py", line 364, in test_connection_no_rsa_pss
    settings=settings)
  File "/home/travis/build/tomato42/tlslite-ng/tlslite/utils/deprecations.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "/home/travis/build/tomato42/tlslite-ng/tlslite/tlsconnection.py", line 381, in handshakeClientCert
    for result in handshaker:
  File "/home/travis/build/tomato42/tlslite-ng/tlslite/tlsconnection.py", line 399, in _handshakeClientAsync
    for result in self._handshakeWrapperAsync(handshaker, checker):
  File "/home/travis/build/tomato42/tlslite-ng/tlslite/tlsconnection.py", line 3328, in _handshakeWrapperAsync
    for result in handshaker:
  File "/home/travis/build/tomato42/tlslite-ng/tlslite/tlsconnection.py", line 613, in _handshakeClientAsyncHelper
    nextProto):
  File "/home/travis/build/tomato42/tlslite-ng/tlslite/tlsconnection.py", line 1529, in _clientFinished
    for result in self._sendFinished(masterSecret, cipherSuite, nextProto):
  File "/home/travis/build/tomato42/tlslite-ng/tlslite/tlsconnection.py", line 3271, in _sendFinished
    self.sock.flush()
  File "/home/travis/build/tomato42/tlslite-ng/tlslite/bufferedsocket.py", line 50, in flush
    self.socket.sendall(buf)
error: [Errno 32] Broken pipe
----------------------------------------------------------------------
Ran 1341 tests in 14.425s
```

**Comment by tomato42** [comment]
no problems for few months now, closing as fixed
