### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by rominf** [tomato42/tlslite-ng#320]
I have following code:
```python
from tlslite.utils import keyfactory
...
privatekey = keyfactory.parsePrivateKey(privateKeyString)
```

It fails with this:
```
Traceback (most recent call last):
  File "app.py", line 66, in <module>
    resp, content = client.request(request_token_url, "POST")
  File "/home/rominf/.pyenv/versions/kgjirabot/lib/python3.6/site-packages/oauth2/__init__.py", line 673, in request                                                   
    req.sign_request(self.method, self.consumer, self.token)
  File "/home/rominf/.pyenv/versions/kgjirabot/lib/python3.6/site-packages/oauth2/__init__.py", line 502, in sign_request                                              
    self['oauth_signature'] = signature_method.sign(self, consumer, token)
  File "app.py", line 34, in sign
    signature = privatekey.hashAndSign(raw)
  File "/home/rominf/.pyenv/versions/kgjirabot/lib/python3.6/site-packages/tlslite/utils/rsakey.py", line 80, in hashAndSign                                           
    hashBytes = secureHash(bytearray(bytes), hAlg)
TypeError: string argument without an encoding
```

**Comment by tomato42** [comment]
`hashAndSign()` doc says "Hash and sign the passed-in bytes."

the data to be signed must be serialised to bytes before signing

**Comment by rominf** [comment]
OK, thanks!
