### ISSUE TITLE
Running examples on v0.8.0-alpha21 fails

### ISSUE THREAD

**Issue by vladikoff** [tomato42/tlslite-ng#325]
Any ideas?

Server:

```
python ../scripts/tls.py server -k serverX509Key.pem -c serverX509Cert.pem -t TACK1.pem localhost:4443
I am an HTTPS test server, I will listen on localhost:4443
Serving files from /Users/vladikoff/mozilla/tlslite-ng/tests
Using certificate and private key...
About to handshake...
../scripts/tls.py:511: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  start = time.clock()
../scripts/tls.py:529: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  stop = time.clock()
  Handshake time: 0.116 seconds
  Version: TLS 1.3
  Cipher: aes256gcm python
  Ciphersuite: TLS_AES_256_GCM_SHA384
  No client certificate provided by peer
  Server X.509 SHA1 fingerprint: c4365fbd94328a333738035c12d2459bdb323a29
  Group used for key exchange: secp256r1
  SNI: localhost
  Next-Protocol Negotiated: None
  Encrypt-then-MAC: False
  Extended Master Secret: True
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 49754)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "/Users/vladikoff/mozilla/tlslite-ng/venv/lib/python3.7/site-packages/tlslite/integration/tlssocketservermixin.py", line 56, in finish_request
    self.RequestHandlerClass(tlsConnection, client_address, self)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/server.py", line 646, in __init__
    super().__init__(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 717, in __init__
    self.handle()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/server.py", line 394, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/Users/vladikoff/mozilla/tlslite-ng/venv/lib/python3.7/site-packages/tlslite/tlsrecordlayer.py", line 499, in recv_into
    data = self.read(len(b))
  File "/Users/vladikoff/mozilla/tlslite-ng/venv/lib/python3.7/site-packages/tlslite/tlsrecordlayer.py", line 250, in read
    for result in self.readAsync(max, min):
  File "/Users/vladikoff/mozilla/tlslite-ng/venv/lib/python3.7/site-packages/tlslite/tlsrecordlayer.py", line 277, in readAsync
    allowedHsTypes):
  File "/Users/vladikoff/mozilla/tlslite-ng/venv/lib/python3.7/site-packages/tlslite/tlsrecordlayer.py", line 695, in _getMsg
    for result in self._getNextRecord():
  File "/Users/vladikoff/mozilla/tlslite-ng/venv/lib/python3.7/site-packages/tlslite/tlsrecordlayer.py", line 927, in _getNextRecord
    for result in self._getNextRecordFromSocket():
  File "/Users/vladikoff/mozilla/tlslite-ng/venv/lib/python3.7/site-packages/tlslite/tlsrecordlayer.py", line 961, in _getNextRecordFromSocket
    for result in self._recordLayer.recvRecord():
  File "/Users/vladikoff/mozilla/tlslite-ng/venv/lib/python3.7/site-packages/tlslite/recordlayer.py", line 872, in recvRecord
    for result in self._recordSocket.recv():
  File "/Users/vladikoff/mozilla/tlslite-ng/venv/lib/python3.7/site-packages/tlslite/recordlayer.py", line 208, in recv
    for record in self._recvHeader():
  File "/Users/vladikoff/mozilla/tlslite-ng/venv/lib/python3.7/site-packages/tlslite/recordlayer.py", line 142, in _recvHeader
    for result in self._sockRecvAll(1):
  File "/Users/vladikoff/mozilla/tlslite-ng/venv/lib/python3.7/site-packages/tlslite/recordlayer.py", line 119, in _sockRecvAll
    socketBytes = self.sock.recv(length - len(buf))
  File "/Users/vladikoff/mozilla/tlslite-ng/venv/lib/python3.7/site-packages/tlslite/bufferedsocket.py", line 54, in recv
    return self.socket.recv(bufsize)
ConnectionResetError: [Errno 54] Connection reset by peer
----------------------------------------
```

Client:

```
 python tls.py client localhost:4443
tls.py:351: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  start = time.clock()
tls.py:358: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  stop = time.clock()
Handshake success
  Handshake time: 0.101 seconds
  Version: TLS 1.3
  Cipher: aes256gcm python
  Ciphersuite: TLS_AES_256_GCM_SHA384
  No client certificate provided by peer
  Server X.509 SHA1 fingerprint: c4365fbd94328a333738035c12d2459bdb323a29
  Group used for key exchange: secp256r1
  SNI: localhost
  Next-Protocol Negotiated: None
  Encrypt-then-MAC: False
  Extended Master Secret: True
Traceback (most recent call last):
  File "tls.py", line 568, in <module>
    clientCmd(sys.argv[2:])
  File "tls.py", line 385, in clientCmd
    connection.send("GET / HTTP/1.0\r\n\r\n")
  File "/Users/vladikoff/mozilla/tlslite-ng/venv/lib/python3.7/site-packages/tlslite/tlsrecordlayer.py", line 477, in send
    self.write(s)
  File "/Users/vladikoff/mozilla/tlslite-ng/venv/lib/python3.7/site-packages/tlslite/tlsrecordlayer.py", line 328, in write
    for result in self.writeAsync(s):
  File "/Users/vladikoff/mozilla/tlslite-ng/venv/lib/python3.7/site-packages/tlslite/tlsrecordlayer.py", line 346, in writeAsync
    applicationData = ApplicationData().create(bytearray(s))
TypeError: string argument without an encoding
```

Details:

```
(venv) ➜  tlslite-ng git:(master) ✗ python --version
Python 3.7.1
```

Make test output:

```
(venv) ➜  tlslite-ng git:(master) ✗ make test
python tests/tlstest.py server localhost:4433 tests & sleep 4
python tests/tlstest.py client localhost:4433 tests
Test 0 - anonymous handshake
Test 0 - Anonymous server handshake
Test 1 - good X.509 (plus SNI)
Test 1 - good X509 (plus SNI)
Test 2 - good X.509 TLSv1.2 (plus ALPN)
Test 2 - good X509 TLSv1.2 (plus ALPN)
Test 3 - good X.509 TLSv1.3 (plus ALPN)
Test 3 - good X509 TLSv1.3 (plus ALPN)
Test 4 - good X.509/w RSA-PSS sig
Test 4 - good X.509/w RSA-PSS cert
Test 5 - good X.509/w RSA-PSS cert
Test 5 - good X.509/w RSA-PSS sig
Test 6 - good X.509, SSL v3
Test 6 - good X509, SSLv3
Test 7 - good X.509, mismatched key_share
Test 7 - good X.509, mismatched key_share
Test 8 - good X.509, RC4-MD5
Test 8 - good X509, RC4-MD5
Test 9 - good X.509, TACK...skipped (no tackpy)
Test 10 - good X.509, TACK unrelated to cert chain...skipped (no tackpy)
Test 11 - good PSK
Test 9 - good X.509, TACK...skipped (no tackpy)
Test 10 - good X.509, TACK unrelated to cert chain...skipped (no tackpy)
Test 11 - good PSK
Test 12 - good PSK, no DH
Test 12 - good PSK, no DH
Test 13 - good PSK, no DH, no cert
Test 13 - good PSK, no DH, no cert
Test 14 - good SRP (db)
server 1544571564.3581 - tmp file created
server 1544571564.358127 - tmp file closed
server 1544571564.358216 - tmp file removed
server 1544571564.358248 - verifier initialised
DEBUG:tlslite.basedb:server 1544571564.3582919 - create - will open db
DEBUG:tlslite.basedb:server 1544571564.360678 - create - setting type
DEBUG:tlslite.basedb:server 1544571564.360737 - create - syncing
Traceback (most recent call last):
  File "tests/tlstest.py", line 1227, in serverTestCmd
    verifierDB.create()
  File "/Users/vladikoff/mozilla/tlslite-ng/venv/lib/python3.7/site-packages/tlslite/basedb.py", line 42, in create
    self.db.sync()
AttributeError: '_dbm.dbm' object has no attribute 'sync'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests/tlstest.py", line 1242, in serverTestCmd
    os.remove(db_name)
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/cv/w3cp7lkj6bq70z90s51jllsc0000gn/T/tmps1b14u8e'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests/tlstest.py", line 1761, in <module>
Test 14 - good SRP (db)
client 1544571564.362445 - waiting for synchro
    serverTestCmd(sys.argv[2:])
  File "tests/tlstest.py", line 1246, in serverTestCmd
    os.remove(db_name + ".dat")
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/cv/w3cp7lkj6bq70z90s51jllsc0000gn/T/tmps1b14u8e.dat'
client 1544571564.365994 - synchro received
Traceback (most recent call last):
  File "tests/tlstest.py", line 1759, in <module>
    clientTestCmd(sys.argv[2:])
  File "tests/tlstest.py", line 325, in clientTestCmd
    connection = connect()
  File "tests/tlstest.py", line 101, in connect
    sock.connect(address)
ConnectionRefusedError: [Errno 61] Connection refused
make: *** [test] Error 1
```

**Comment by tomato42** [comment]
> `TypeError: string argument without an encoding`

ah, yes, I forgot to use bytestring in tls.py, this should fix it: #326

> AttributeError: '_dbm.dbm' object has no attribute 'sync'

that I have no idea where it comes from... those are exactly the same tests I'm running in CI: https://travis-ci.org/tomato42/tlslite-ng/jobs/466028735#L677

some compatibility issue with installed packages?

**Comment by vladikoff** [comment]
I went back to Python 2 and that fixed the issue, examples ran correctly!

**Comment by tomato42** [comment]
but they should run with python 3 - both are supported

**Comment by tomato42** [comment]
Anything problematic left?

**Comment by vladikoff** [comment]
@tomato42 I was just sticking to python2 for now, should I try latest `master` with python 3 and see if it works now?

**Comment by tomato42** [comment]
yes, please check

**Comment by tomato42** [comment]
@vladikoff any update?

**Comment by vladikoff** [comment]
hey, sorry I missed the notification. all tests are good on latest master now . Thank you!
